[package]
name = "font-scaler-bak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fontdue = "0.9.2"
glium = "0.34.0"
glutin = "0.32.0"
opentype = "0.37.1"
rusttype = "0.9.3"
ttf-parser = "0.21.1"
